# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/karl/scripts-heydok/python/Heydok GIT Projects/vnstatgui/resources/myplot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myplot(object):
    def setupUi(self, myplot):
        myplot.setObjectName("myplot")
        myplot.resize(650, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/karl/scripts-heydok/python/Heydok GIT Projects/vnstatgui/resources/icon.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        myplot.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(myplot)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = MplWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 59, 591, 291))
        self.widget.setObjectName("widget")
        myplot.setCentralWidget(self.centralwidget)

        self.retranslateUi(myplot)
        QtCore.QMetaObject.connectSlotsByName(myplot)

    def retranslateUi(self, myplot):
        _translate = QtCore.QCoreApplication.translate
        myplot.setWindowTitle(_translate("myplot", "My Plot"))
from .mplwidget import MplWidget
